calm/schema/core.json

to be definitions per #12 .
Also updated $id to match GH raw hosting location to work with json schema in IDEA.

Refactor nodes and relationships

---

calm/draft/2024-03/meta/core.json
calm/pattern/api-gateway.json
calm/samples/api-gateway-implementation.json
calm/samples/traderx/traderx.json
calm/samples/traderx/traderx.yaml

Ensure consistent naming convention in CALM

---

calm/samples/traderx/traderx.json
calm/samples/traderx/traderx.yaml

Doesn't address external node question).
@Budlee / @aidanm3341 I think these changes should rectify the issues you were both having. Would be great to see the updated visualisations in case I've missed something.
Also, I've duplicated some relationships to match the C4 design, although suspect we may need to think about how we may want to address this without the duplication.

Update TraderX samples inline with the C4. Part of response to #47 

---

.github/workflows/translator.yml
translator/src/test/java/org/finos/calmtranslator/translators/TestC4ModelTranslatorShould.java

This should fix the translator GitHub action, it includes a breaking test to validate which must be removed before the merge.

Translator action fix

---

.github/workflows/spectral-validation.yml
spectral/examples/bad-rest-api.json

Adds a spectral action for issue #35 - does this by manually installing Spectral.

#35 Add manual spectral action 

---

calm/draft/2024-04/meta/calm.json
calm/draft/2024-04/meta/core.json

Copy over to April version of schema

---

calm/draft/2024-04/meta/core.json

Fixing reference to interface type specified in the defs of the interface.json file

issue-48 - fixing reference to interface-type

---

cli/package-lock.json
cli/package.json
cli/src/commands/validate/validate.spec.ts
cli/src/commands/validate/validate.ts
cli/src/index.ts
cli/test_fixtures/api-gateway-implementation-that-does-not-match-schema.json
cli/test_fixtures/api-gateway-implementation-that-does-not-pass-the-spectral-validation.json
cli/test_fixtures/api-gateway-implementation.json
cli/test_fixtures/calm.json
cli/test_fixtures/calm/calm.json
cli/test_fixtures/calm/core.json
cli/test_fixtures/core.json
cli/test_fixtures/markdown.md

Adding validate function that can validate a JSON schema against an instantiation. The meta schema can be provided as an argument.

Issue 73 - adding validate command to cli

---

cli/jest.config.js
cli/src/commands/generate/generate.spec.ts
cli/src/commands/generate/generate.ts
cli/src/commands/helper.ts
cli/src/commands/validate/validate.spec.ts
cli/src/commands/validate/validate.ts
cli/src/commands/visualize/visualize.ts
cli/src/index.ts

Switching from using console.log to use the winston logger

Issue 73 - Switching from console log to winston logger

---

README.md

Add lead maintainers and meeting details to the main README.

---

.github/workflows/cve-scanning-node.yml
.github/workflows/license-scanning-node.yml

removed the reference to the top level visualizer directory

Fix visualizer scanning

---

README.md

Add OpenSSF badge

---

cli/src/commands/generate/components/node.ts
cli/src/commands/generate/components/property.spec.ts
cli/src/commands/generate/components/property.ts
cli/src/commands/generate/generate.ts

Improve logging and instantiate ref properties

---

.github/CODEOWNERS
spectral/instantiation/functions/ids-are-unique.js
spectral/instantiation/validation-rules.yaml
spectral/pattern/functions/ids-are-unique.js
spectral/pattern/validation-rules.yaml

Requested by @jpgough-ms .
Also adds @jpgough-ms as a CODEOWNER on spectral and the CLI.

Spectral rule to detect duplicated unique IDs

---

.github/workflows/npm.yml

This populates the dist folder prior to publishing the package to npm

add build step before publishing

---

cli/package-lock.json
cli/package.json

bumped some outdated versions with 'npm update' and increased patch version

CLI version updates

---

docs/package-lock.json
docs/package.json

some people had a similar issue as what we have in the GH action, their fix was explicitly adding this lib to the package.json so I thought I'd give it a go https://github.com/oven-sh/bun/issues/2257

explicitly added @docusaurus/react-loadable to package.json

---

cli/src/commands/validate/validate.spec.ts
cli/src/commands/validate/validate.ts

- Sorting the output of calm validate command to return errors first

issue-315 - sorting validate command output to print errors first

---

.github/node-cve-ignore-list.xml
cli/package-lock.json
cli/package.json

Suppress CVE-2023-29827 per https://github.com/mde/ejs/issues/720

Fix CVE-2024-45296

---

cli/package-lock.json
cli/package.json

https://github.com/advisories/GHSA-gcx4-mw62-g8wm

Force override of rollup to resolve (see url in comments)

---

docs/README.md

Update README.md to link to the docs instead of the default readme page

Update README.md to link to the docs instead of the default readme

---

calm/draft/2024-09/meta/calm.json
calm/draft/2024-09/meta/control-requirement.json
calm/draft/2024-09/meta/control.json
calm/draft/2024-09/meta/core.json
calm/draft/2024-09/meta/evidence.json
calm/draft/2024-09/meta/interface.json

Create 2024-09 draft and change base URI

---

cli/src/index.ts

Global install (with @finos/calm-cli/0.2.0)
```shell
% calm --version 
0.1.0
```
With patch
```shell
% npx calm --version
0.2.1
```
THIS SOFTWARE IS CONTRIBUTED SUBJECT TO THE TERMS OF THE FINOS Corporate Contributor License Agreement.
THIS SOFTWARE IS LICENSED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTY OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) …

calm --version to return from package.json

---

.github/workflows/cve-scanning-maven.yml
.github/workflows/cve-scanning-node.yml
docs/package-lock.json
docs/package.json

Also updating the CVE actions to run on PRs

Fix cookie vuln - https://github.com/advisories/GHSA-pxg6-pf52-xh8x

---

.github/workflows/spectral-validation.yml
calm/draft/2024-10/meta/flow.json
calm/samples/traderx/controls/flow-sla-control-requirement.json
calm/samples/traderx/flows/add-update-account/add-update-account-control-configuration.json
calm/samples/traderx/flows/add-update-account/add-update-account.json
calm/samples/traderx/flows/bootstrapping-position-blotter/bootstrapping-position-blotter.json
calm/samples/traderx/flows/load-list-of-accounts/load-list-of-accounts.json
calm/samples/traderx/flows/submit-trade-ticket/submit-trade-ticket-control-configuration.json
calm/samples/traderx/flows/submit-trade-ticket/submit-trade-ticket.json
calm/samples/traderx/flows/trade-processing/trade-processing-control-configuration.json
calm/samples/traderx/flows/trade-processing/trade-processing-new-trade.json
calm/samples/traderx/flows/trade-processing/trade-processing-update-trade.json
calm/samples/traderx/traderx.json

This PR introduces a new schema for defining business flows and their requirements within the CALM framework.  It
Defined Flow Schema: A new JSON schema (flow.json) represents business flows. This schema outlines the structure for capturing business flows and associated control requirements. 
This is a follow up to https://github.com/finos/architecture-as-code/pull/430/ which was closed due to issues with easyCLA.
It contains the following changes since that PR
1. For this initial commit, flow definitions are separate to the core CALM model (similar to the way evidence.json works)
2. It removes related concepts associated with data.
3. It contains examples for traderX based on https://github.com/finos/traderX/blob/main/docs/flows.md. For now I have kept relationships of traderx the same, …

Add flow specification with traderx examples

---

.github/workflows/s3-docs-sync.yml

The sync failed, I think this is because I'd set the working directory to be docs

Update sync command

---

cli/package-lock.json
cli/package.json

This should close two of the warnings from #275 
Have bumped the incremental version so we can publish to npm to check.

Resolve inflight and glob warnings from npm

---

cli/package-lock.json
cli/package.json
cli/src/index.ts

Referencing a file (in our case package.json) outside of the TS project has changed the dist structure, pushing the commands below /src. Reverting that change to fix the CLI.

Fix CLI issue caused from resolving version from package.json

---

docs/talks/index.md

PR includes video of CALM - Architecture at Scale by Denis Coffaro, Morgan Stanley, and David Johnston, Red Hat, Open Source in Finance Forum, NYC 2025.

#502 Update Documentation to include OSFF NYC 2025 video

---

cli/package-lock.json
video/aasc-wg-2024-09-24.mov

Updating visualizer branch to remove video

Updating visualizer branch to remove video

---

.github/workflows/publish-cli-to-npm.yml
cli/README.md

Also updated README to reflect how to trigger a release.

#595 - updated action to work under workspaces.

---

cli/README.md
cli/package.json
cli/src/cli.spec.ts
package-lock.json
package.json

Now that I know more about workspaces, the published CLI didn't have a bin element so wasn't being linked as part of the release/install.
Also ran lint-fix - so some other line ending fixes.

Workspace Bin Movement

---

cli/README.md
cli/jest.config.js
cli/package.json
cli/src/cli.spec.ts
cli/src/index.ts
cli/test_fixtures/validate_output_pretty.txt
cli/tsup.config.ts
cli/watch.mjs
package-lock.json
shared/jest.config.js
shared/package.json
shared/src/commands/validate/output-formats/junit-output.spec.ts
shared/src/commands/validate/output-formats/junit-output.ts
shared/src/commands/validate/output-formats/pretty-output.spec.ts
shared/src/commands/validate/output-formats/pretty-output.ts
shared/src/commands/validate/validate.spec.ts
shared/src/commands/validate/validate.ts
shared/src/index.ts

Introducing a `-pretty` flag to the validate command.
Also introduced the ability to `watch` coupled with `tsup`. While ideally these wouldn't be coupled into one PR I made sure `watch` was working when developing this very PR.

Pretty Human Readable Output of Validate CLI

---

calm-hub/README.md
calm-hub/src/main/docker/Dockerfile.jvm

Published Image already fixed by @jpgough-ms

add mac silicon support to docker build commands (#723)

---

calm-hub/src/main/java/org/finos/calm/resources/ArchitectureResource.java
calm-hub/src/main/java/org/finos/calm/resources/PatternResource.java
calm-hub/src/test/java/org/finos/calm/resources/TestArchitectureResourceShould.java
calm-hub/src/test/java/org/finos/calm/resources/TestPatternResourceShould.java

Add JsonProcessingException error tests (#732)

---

.github/labeler.yml
.github/workflows/pr-labelling.yml

Ensure that changes being made in PR's are labelled based on the module being modified.

#783 Pr Labelling

---

calm-visualizer/package.json
calm-visualizer/src/components/cytoscape-renderer/CytoscapeRenderer.tsx
calm-visualizer/src/components/drawer/Drawer.tsx
calm-visualizer/src/components/sidebar/Sidebar.tsx
calm-visualizer/src/tests/Sidebar.test.tsx
package-lock.json
package.json
shared/src/commands/visualize/calmToDot.spec.ts
shared/src/types.ts

Updated the layout engine to try something new, I think its much better.
Also in the latest CALM draft relationships use 'unique-id' not 'uniqueId', so I think the types were just outdated and I have updated.
still not perfect, but an improved layout

Improve Visualizer Layout

---

calm-visualizer/package-lock.json
calm-visualizer/package.json
calm-visualizer/src/components/cytoscape-renderer/CytoscapeRenderer.tsx
calm-visualizer/src/components/navbar/Navbar.css
calm-visualizer/src/components/navbar/Navbar.tsx
package-lock.json

Please see latest screenshot below:

Adjusted styling on zoom controls in CALM Visualizer

---

calm-hub/pom.xml
calm-hub/src/integration-test/java/integration/MongoAdrIntegration.java
calm-hub/src/main/java/org/finos/calm/domain/adr/Adr.java
calm-hub/src/main/java/org/finos/calm/domain/adr/AdrMeta.java
calm-hub/src/main/java/org/finos/calm/domain/adr/Decision.java
calm-hub/src/main/java/org/finos/calm/domain/adr/Link.java
calm-hub/src/main/java/org/finos/calm/domain/adr/NewAdrRequest.java
calm-hub/src/main/java/org/finos/calm/domain/adr/Option.java
calm-hub/src/main/java/org/finos/calm/resources/AdrResource.java
calm-hub/src/main/java/org/finos/calm/store/mongo/MongoAdrStore.java
calm-hub/src/test/java/org/finos/calm/resources/TestAdrResourceShould.java
calm-hub/src/test/java/org/finos/calm/store/mongo/TestMongoAdrStoreShould.java

Removed Record Builder annotations (#716)

---

.github/workflows/pr-labelling.yml

Reverts finos/architecture-as-code#853
Labeler is erroring after update

Revert "chore(deps): update actions/labeler action to v5"

---

package-lock.json
shared/package.json

Intended to address - https://github.com/finos/architecture-as-code/security/dependabot/45

Upgrade jsonpath-plus

---

renovate.json

I am not a fan of main to main - but it's a tiny PR so I'll let it go for now.

Update renovate configuration - to include dependencyDashboard.

---

calm/draft/2025-03/prototype/anyof/both-options.architecture.json
calm/draft/2025-03/prototype/anyof/neither-option.architecture.json
calm/draft/2025-03/prototype/anyof/options-prototype.pattern.json
calm/draft/2025-03/prototype/oneof/application-a.architecture.json
calm/draft/2025-03/prototype/oneof/application-b.architecture.json
calm/draft/2025-03/prototype/oneof/options-prototype.pattern.json
shared/src/model/relationship.spec.ts
shared/src/model/relationship.ts
shared/src/types/core-types.ts

- To help with understanding the feature, I've also added a prototype showing the 'anyOf' variation of pattern options.
- I've also updated the shared CALM Model to include the new relationship type.

Pattern Options Extra Example + Model Updates

---

calm/draft/2025-03/meta/core.json
calm/draft/2025-03/prototype/anyof/options-prototype.pattern.json
calm/draft/2025-03/prototype/oneof/options-prototype.pattern.json
cli/test_fixtures/generate_output.json
shared/src/commands/generate/components/instantiate.spec.ts
shared/src/commands/generate/components/property.spec.ts
shared/src/commands/generate/components/property.ts
shared/src/docify/docifier.e2e.spec.ts
shared/src/docify/graphing/c4.spec.ts
shared/src/docify/graphing/c4.ts
shared/src/docify/template-bundles/docusaurus/docusaurus-transformer.ts
shared/src/docify/template-bundles/docusaurus/index.md.hbs
shared/src/docify/template-bundles/docusaurus/relationships.hbs
shared/src/docify/template-bundles/docusaurus/sidebar.js.hbs
shared/test_fixtures/command/generate/expected-output/conference-secure-signup.arch.json
shared/test_fixtures/command/generate/expected-output/conference-signup.arch.json

This PR introduces several improvements and fixes to the `calm docify` endpoint to enhance robustness and extend support for additional relationship types.
- **C4 and Relationship Graph Diagrams**  
Added support for the `DeployedIn` relationship type. This enables proper rendering of parent-child hierarchies when systems or services are deployed into environments.
- **Graceful Handling of Empty Flows**  
The documentation site will no longer fail to load when no flows are defined in the CALM model. This makes the rendering process more resilient to partial or minimal models.
- **Avoid Handlebars/MDX Conflict**  
To prevent clashes between Handlebars (`{{ }}`) and MDX parsing during documentation rendering, the `calm-template` placeholder syntax has been updated to use `[[ ]]`.  
This …

Docify Enhancements for QCon

---

cli/package.json

Fixes issue with schema ID being generated incorrectly (#1202)

Bump patch version for bugfix

---

cli/package.json

(fixes #1208) update license in CLI package.json to be Apache-2.0

(fixes #1208) update license in CLI package.json to be Apache-2.0

---

calm/draft/1232/meta/core.json

Addresses: #1232 / #1178 / #1181

Propose change to node-type-definition and associate changes

---

calm-hub/src/test/java/org/finos/calm/domain/adr/TestDecisionShould.java
calm-hub/src/test/java/org/finos/calm/domain/adr/TestNewAdrRequestShould.java

Fix build when run without integration test profile. 

---

calm-hub-ui/src/visualizer/components/drawer/Drawer.test.tsx
calm-hub-ui/src/visualizer/components/menu/Menu.test.tsx
calm-hub-ui/src/visualizer/components/sidebar/Sidebar.test.tsx
calm-hub-ui/src/visualizer/helpers/set-functions.test.ts
calm-hub-ui/src/visualizer/services/layout-correction-service.test.ts

just moving tests to be colocated with their implementations which is the standard we follow in the rest of the repo

move tests to be with their implementations

---

calm-hub/pom.xml
calm-hub/src/main/java/org/finos/calm/resources/ArchitectureResource.java
calm-hub/src/main/java/org/finos/calm/resources/PatternResource.java
calm-hub/src/main/java/org/finos/calm/resources/ResourceValidationConstants.java
calm-hub/src/test/java/org/finos/calm/resources/TestArchitectureResourcePutEnabledShould.java
calm-hub/src/test/java/org/finos/calm/resources/TestArchitectureResourceShould.java
calm-hub/src/test/java/org/finos/calm/resources/TestPatternResourcePutEnabledShould.java
calm-hub/src/test/java/org/finos/calm/resources/TestPatternResourceShould.java

Adds input constraints and XSS sanitization to Architecture and Pattern endpoints (#761)
There will be a follow up PR for flows.

Adds input constraints and XSS sanitization to Architecture and Pattern endpoints

---

cli/package.json

Minor release containing some calm-docify enhancements around relationships, inline-control and flow rendering

New cli version containing docify enhancements

---

.github/workflows/s3-sync.yml
calm/getting-started/README.md
calm/getting-started/conference-signup.pattern.json
calm/getting-started/controls/micro-segmentation.config.json
calm/getting-started/controls/micro-segmentation.requirement.json
calm/getting-started/controls/permitted-connection-http.config.json
calm/getting-started/controls/permitted-connection-jdbc.config.json
calm/getting-started/controls/permitted-connection.requirement.json

Initial steps for getting-started with placeholder README.md. To be spruced up.

Add initial documentation for getting started

---

cli/src/cli.e2e.spec.ts
cli/src/cli.spec.ts
cli/src/cli.ts
cli/src/command-helpers/validate.spec.ts
cli/src/command-helpers/validate.ts
cli/src/index.spec.ts
cli/src/server/cli-server.integration.spec.ts
cli/src/server/cli-server.ts
cli/src/server/routes/validation-route.ts
cli/test_fixtures/validate_output_pretty.txt
cli/vitest.config.ts
shared/src/commands/validate/validate.spec.ts
shared/src/commands/validate/validate.ts
shared/src/docify/template-bundles/docusaurus/docusaurus.config.js
shared/vitest.config.ts

This is the first stage before I refactor to inject schema directory properly

Validate refactor part 1 - move loading of files out to CLI

---

cli/src/cli.e2e.spec.ts

Fix https://github.com/finos/architecture-as-code/security/code-scanning/40

Fix shell vulnerability

---

docs/package.json
package-lock.json
package.json

Fix https://github.com/finos/architecture-as-code/security/dependabot/70

Resolve on-headers vulnerability

---

renovate.json

`:dependencyDashboard` - Creates a GitHub issue dashboard for visibility and manual control over updates
`:semanticCommits` - Uses conventional commit format for better Git history and automated changelog generation
`:separateMajorReleases` - Individual PRs for major updates to prevent blocking and enable focused review
`:combinePatchMinorReleases` - Groups related patch/minor updates to reduce PR noise
`:ignoreUnstable` - Skips pre-release versions to maintain stability
`:prImmediately + :updateNotScheduled` - Enables fast security updates while respecting rate limits
`helpers:pinGitHubActionsByDigest` - Pins GitHub Actions by SHA for supply chain security

chore(deps): update renovate config

---

cli/package.json
cli/src/cli.e2e.spec.ts
package-lock.json

new schema is automatically bundled. Just need to bump CLI version to publish it

bump cli version to include v1 schema

---

shared/src/commands/validate/validate.e2e.spec.ts
shared/src/commands/validate/validate.spec.ts
shared/src/commands/validate/validate.ts
shared/test_fixtures/command/validate/options/arch.json
shared/test_fixtures/command/validate/options/pattern-resolved.json
shared/test_fixtures/command/validate/options/pattern.json

Resolve #1555 by preprocessing a pattern against the chosen options documented in an architecture that was generated from it. This turns the pattern into one that can be used for validating.
The same option handling code used in `calm generate` is now used in `calm validate`, so little new code is added in this PR.
Tests have been added, drawn from the examples in #1555 
AI was utilised in a limited manner in production of this change.

fix(shared): validation of architectures against patterns with options (finos#1555)

---

commitlint.config.js

fix(commitlint): add footer line length enforcement for semantic-release

---

.github/workflows/automated-release.yml
cli/.releaserc.json
cli/package.json
package-lock.json

feat(release): add automated changelog PR creation for CLI releases

---

cli/.releaserc.json

fix(release): swap @semantic-release/exec and @semantic-release/github

---

calm-widgets/README.md
calm-widgets/src/widgets.e2e.spec.ts
calm-widgets/src/widgets/table/index.spec.ts
calm-widgets/src/widgets/table/index.ts
calm-widgets/src/widgets/table/row-template.html
calm-widgets/src/widgets/table/table-horizontal.html
calm-widgets/src/widgets/table/table-template.html
calm-widgets/src/widgets/table/table-vertical.html
calm-widgets/test-fixtures/table-widget/flat-vertical-table/context.json
calm-widgets/test-fixtures/table-widget/flat-vertical-table/expected.md
calm-widgets/test-fixtures/table-widget/flat-vertical-table/template.hbs
calm-widgets/test-fixtures/table-widget/simple-object/expected.md
calm-widgets/test-fixtures/table-widget/simple-object/template.hbs
cli/test_fixtures/template/expected-output/widget-tests/sad-test.md
cli/test_fixtures/template/expected-output/widget-tests/table-test.md

Minor enhancement to add support for flat vertical tables and a JSON/flow rendering fixture for the table widget. Changes include new/updated table templates, row/horizontal/vertical rendering, and accompanying test fixtures and expectations used by the CLI snapshot tests.
- calm-widgets (src)
- Modified: src/widgets.e2e.spec.ts, src/widgets/table/index.spec.ts, src/widgets/table/index.ts, src/widgets/table/row-template.html, src/widgets/table/table-template.html
- Added: src/widgets/table/table-horizontal.html, src/widgets/table/table-vertical.html
- calm-widgets (test fixtures)
- Added fixtures: test-fixtures/table-widget/flat-vertical-table/{context.json,expected.md,template.hbs}
- Added fixtures: test-fixtures/table-widget/flow-json/{context.json,expected.md,template.hbs}
- Modified …

feat(calm-widgets): table enhancements to allow user to create a vertical orientated table

---

cli/CHANGELOG.md

docs(cli): update changelog for 1.1.0 [skip ci]

---

calm-ai/CALM.chatmode.md
calm-ai/README.md
calm-ai/package.json
calm-ai/tools/architecture-creation.md
calm-ai/tools/control-creation.md
calm-ai/tools/documentation-creation.md
calm-ai/tools/flow-creation.md
calm-ai/tools/interface-creation.md
calm-ai/tools/metadata-creation.md
calm-ai/tools/node-creation.md
calm-ai/tools/pattern-creation.md
calm-ai/tools/relationship-creation.md
cli/README.md
cli/package.json
cli/src/cli.ts
cli/src/command-helpers/ai-tools.spec.ts
cli/src/command-helpers/ai-tools.ts
package-lock.json
package.json

Addresses #1628
- Introduced `pattern-creation.md` with comprehensive guidelines for creating CALM patterns, including structure, options, examples, and best practices.
- Added `relationship-creation.md` detailing the creation of relationships, required properties, usage patterns, and validation rules.
- Enhanced CLI with `copilot-chatmode` command for AI assistance in CALM architecture modeling, including setup instructions and tool prompts.
- Updated CLI README to include new command and usage details for CALM AI assistance.
- Modified CLI build scripts to copy AI tools and related documentation.
- Implemented new command helper for setting up AI tools, including chatmode configuration and tool prompt files.
- Updated package configurations to include `calm-ai` workspace and …

Add CALM Chatmode for VSCode users via the CLI

---

cli/.releaserc.json

feat(calm-ai): Add release rules and scope for calm-ai in semantic release configuration

feat(calm-ai): Add release rules and scope for calm-ai 

---

calm-ai/CALM.chatmode.md

feat(calm-ai): Add 'runInTerminal' tool to CALM assistant configuration

feat(calm-ai): Add 'runInTerminal' tool to CALM assistant configuration

---

shared/src/commands/generate/components/property.spec.ts
shared/src/commands/generate/components/property.ts

feat(property): add default value handling in JsonSchema and related functions

---

calm-plugins/vscode/.vscodeignore
calm-plugins/vscode/DEVELOPER.md
calm-plugins/vscode/LICENSE
calm-plugins/vscode/README.md
calm-plugins/vscode/package.json

Update VSCode marketplace documentation

docs(calm_plugins): Cleanup marketplace documentation entry

---

cli/.releaserc.json

chore(calm-widgets): update release rules and add scope for calm-widgets

---

.github/workflows/automated-release.yml
.github/workflows/publish-cli-on-merge.yml
cli/.releaserc.json

Currently the automated semantic release results in the version update in the package.json happening after the publish to NPM, because we cannot grant permissions for the action to push to main.
This PR changes the process to be two stage, the first to update the version and the second to publish to NPM, with checks to determine that the merge to main was from the automated job.

feat(cli): update automated release workflow to be two stage

---

.github/workflows/cve-scanning-node.yml

fix(ci): Use an environment so we can give access to the oss secrets for PRs from forks
