finos/architecture-as-code

.github/CODEOWNERS

Added @Budlee and @matthewgardner as the codeowners for the translator project.

Add codeowners for translator

---

cli/commands/visualize/visualize.ts
cli/index.ts
cli/package-lock.json
cli/package.json
visualizer/.eslintrc.json
visualizer/.gitignore
visualizer/README.md
visualizer/index.html
visualizer/package-lock.json
visualizer/package.json
visualizer/src/MermaidBuilder.ts
visualizer/src/Types.d.ts
visualizer/src/index.d.ts
visualizer/src/index.ts
visualizer/src/vite-env.d.ts
visualizer/tsconfig.json
visualizer/vite.config.js

This PR adds the code to create a visualisation of a CALM spec in the CLI. The way it is used looks like 
```
calm visualize -i <input-file> -o <output-file>
```
and it outputs an SVG in the specified output file. This SVG can then easily be opened in a browser to be inspected.
Right now the library is just installed from the local repo. Next steps will be to publish both this and the CLI to npm so that we can manage the dependencies correctly.

#42 included initial visualization command in CLI

---

calm/draft/2024-03/meta/core.json

As discussed in #75 the required field is not behaving as expected. As it currently stands, the example patterns are invalid.

issue #75 removing required fields in the meta-schema

---

calm/draft/2024-04/meta/interface.json

With https://github.com/finos-labs/architecture-as-code/pull/106 we have decided to make interfaces optional on a relationship for now. If it was mandatory that would remove the ability to use CALM as a logical tool and mean that it is only a physical modelling tool.
We may need to consider whether we have a convention to mark what type of diagram this is

#48 Remove mandatory interface on connects relationship

---

calm/pattern/api-gateway.json
cli/src/commands/generate/generate.spec.ts
cli/src/commands/generate/generate.ts

Instantiates interfaces when their properties are explicitly listed.
Does not traverse $refs or perform any lookups. 
#110

Interface instantiation of explicit properties

---

cli/src/commands/validate/validate.ts

- Fixing the path to the spectral rules
- Enabling the all errors option for AJV because we want to see all the JSON Schema errors in one run

issue-138 - Enabling the all errors option for AJV

---

cli/src/commands/validate/spectral.result.ts
cli/src/commands/validate/validate.spec.ts
cli/src/commands/validate/validate.ts
cli/src/commands/validate/validation.output.ts

* Unify the output of spectral and Json Schema
* Enabling `strict: 'log'` option when the debug flag is provided
Example of the unified output:
```
info:    Loading meta schema(s) from ../calm/draft/2024-04/meta
info:    Loading pattern from : ../calm/pattern/api-gateway.json
info:    Loading pattern instantiation from : ../calm/samples/api-gateway-implementation.json
error:   The following issues have been found on the JSON Schema instantiation [
{
"code": "connects-relationship-references-existing-nodes",
"severity": "error",
"message": "'api-consumer' does not refer to the unique-id of an existing node.",
"path": "/relationships/0/relationship-type/connects/source/node"
},
{
"code": "json-schema",
"severity": "error",
"message": "must be integer",
"path": "/nodes/0/interfaces/0/port", …
```

Issue-98 - Unify spectral and JSON Schema validation output

---

cli/src/commands/validate/validate.spec.ts
cli/src/commands/validate/validate.ts
cli/test_fixtures/api-gateway-with-no-relationships.json

This PR adds a function to strip `$ref` keys from pattern files and replace them with `ref` when performing Spectral validation.
This change also performs the Spectral validation and includes any errors in the output

Issue #95 - Strip  from patterns when validating with spectral

---

.github/workflows/cli-tests.yml
cli/src/commands/generate/components/property.ts
cli/src/commands/visualize/calmToDot.ts
cli/src/commands/visualize/visualize.spec.ts
cli/src/commands/visualize/visualize.ts
cli/src/index.ts

There are a few small changes I've made here:
- I've updated the GH build action to include running the CLI as part of the tests, this will hopefully help us catch if changes introduce any failures
- To facilitate the previous point, I added proper exit status codes to the visualizer
- The validator defaulted to using a previous meta schema which wasn't compatible with the current sample patterns, I updated that to the latest version
- A recent change which only instantiates required fields broke the visualizer, I've updated it to instantiate all fields when rendering a pattern
- THE PLAGUE OF '**ANY**' STRIKES! A recent change meant that a field which we were assuming was an object (via the use of the 'in' operator) was possibly now just a `string`, but because we had typed that field as …

Visualizer fix

---

cli/package.json

I tested out this bundling on my Mac, and it worked as expected, but apparently the `cp -r` command works different on Mac vs Linux which is a new one for me! This meant that instead of the _contents_ of a folder being copied as I expected, on linux the folder itself was being copied which lead to a different file structure. Removing the trailing slash solves this problem - quite interesting though

fixed file copying bug

---

cli/package.json
cli/src/commands/generate/components/metadata.spec.ts
cli/src/commands/generate/components/metadata.ts
cli/src/commands/generate/components/node.ts
cli/src/commands/generate/generate.spec.ts
cli/src/commands/generate/generate.ts

Adds CLI support to back up changes to spec from #183 . 
If metadata is defined it will recursively attempt to instantiate the objects set within. It will resolve refs too, but only on top-level objects. 
i.e. you can have (approx, missed some detail out)
```json
"metadata": [
{
"$ref": "xyz"
}
]
```
but not 
```json
"metadata": [
{
property: {
"$ref": "xyz"
}
}
]
```
**Note that this also removes support for arbitrary additional top level properties, since this is what metadata replaces.**

Add metadata generation support

---

cli/src/commands/generate/generate.spec.ts
cli/src/commands/generate/generate.ts

Helps identify architecture instantiations after generation. 
Pattern $id -> instantiation $schema, per JSON schema convention

Generate the $schema property from patterns

---

cli/src/commands/validate/spectral.result.ts
cli/src/commands/validate/validate.spec.ts
cli/src/commands/validate/validate.ts
cli/src/index.ts

Add --strict mode

---

calm/samples/api-gateway-instantiation.json
cli/src/commands/validate/validate-pattern-only.spec.ts
cli/src/commands/validate/validate.spec.ts
cli/src/commands/validate/validate.ts
cli/src/index.ts
cli/test_fixtures/bad-schema/bad-json-schema.json

This adds a simple validation mode that checks the provided pattern is valid JSON Schema; this isn't perfect but it gives us some guarantees.
Addresses issue #73 and #317

Add validation feature for patterns only

---

cli/src/commands/generate/components/metadata.spec.ts
cli/src/commands/generate/components/node.spec.ts
cli/src/commands/generate/components/property.spec.ts
cli/src/commands/generate/components/property.ts
cli/src/commands/generate/components/relationship.spec.ts
spectral/instantiation/validation-rules.yaml
spectral/pattern/validation-rules.yaml

Fixes #353. Boolean properties will be output as strings with the value `{{ BOOLEAN_[property name] }}`
We can't output `false` by default because this is a valid option and thus we can't detect it.
I wanted to keep the output valid JSON, so decided to spit out a string.
Also adds
- spectral rule to report boolean placeholders
- spectral rule to warn users that booleans are not recommended if detected in a pattern

#353 correctly instantiate boolean properties and improve spectral rules

---

cli/package.json
cli/src/commands/generate/generate.ts
cli/src/commands/generate/schema-directory.ts
cli/src/commands/validate/validate.ts
cli/src/commands/visualize/visualize.ts
cli/src/index.ts

Resolves #312 
```shell
% npx calm validate                                       
error: required option '-p, --pattern <file>' not specified
% npx calm generate 
error: required option '-p, --pattern <file>' not specified
% npx calm visualize
error: one of required options '-i, --instantiation <file>' or '-p, --pattern <file>' not specified
```

Make CLI errors consistent

---

.vscode/settings.json
calm-visualizer/src/components/fileuploader/FileUploader.tsx

Disable 'visualize' button when no file changes have been made, preventing graph being re-drawn. See screenshot below:

Only re-generate graph if uploaded CALM instance json file has changed (finos#561)

---

calm-visualizer/src/components/fileuploader/FileUploader.tsx
calm-visualizer/src/components/graph/Graph.css
calm-visualizer/src/components/graph/Graph.tsx

See screenshot below:
I've looked further into JSPlump and it seems that it doesn't provide an easy way of preventing overrides of labels out of the box. Will improve in a future PR but also would suggest utilising a different graph library for example D3

Added labels to interactive visualiser (finos#568)

---

cli/src/index.ts

Fixes an issue that means the options for strict and schemadirectory clash on the validate command

Fix strict option clash

---

calm-visualizer/src/components/graph/Graph.css
calm-visualizer/src/components/graph/Graph.tsx

Implement functionality to create groups based on “deployed in” and “composed of” relationships.
**Note:** Additional logic is required to dynamically adjust the size of group containers to fit the nodes they encompass.

Added group and nested group functionality

---

calm/draft/2024-12/meta/core.json
calm/draft/2024-12/meta/flow.json
calm/samples/2024-12/traderx/README.md
calm/samples/2024-12/traderx/controls/flow-sla-control-requirement.json
calm/samples/2024-12/traderx/flows/add-update-account/add-update-account-control-configuration.json
calm/samples/2024-12/traderx/flows/add-update-account/add-update-account.json
calm/samples/2024-12/traderx/flows/load-list-of-accounts/load-list-of-accounts.json
calm/samples/2024-12/traderx/flows/load-positions/load-positions.json
calm/samples/2024-12/traderx/flows/submit-trade-ticket/submit-trade-ticket-control-configuration.json
calm/samples/2024-12/traderx/flows/submit-trade-ticket/submit-trade-ticket.json
calm/samples/2024-12/traderx/flows/trade-processing/trade-processing-control-configuration.json
calm/samples/2024-12/traderx/flows/trade-processing/trade-processing-new-trade.json
calm/samples/2024-12/traderx/flows/trade-processing/trade-processing-update-trade.json
calm/samples/2024-12/traderx/traderx.json

This PR addresses the feature request detailed in issue [650](https://github.com/finos/architecture-as-code/issues/650) by implementing the following enhancements to CALM
1. Adds ecosystem definition to node-type
2. Add flows to core.json. This will allow the eventual traversal of calm-hub by calm-docify
3. It additionally contains some small changes to $id and $url references with the intention that these documents will be hosted network addressable and in calm-hub

Add ecosystem to node spec and tie flows into core.json

---

cli/DEVELOPER_GUIDE.md

- Add details about the version of node, as installation of canvas seems to fail with later versions.
- Update `npx link` to include the folder as it doesn't work without, and clarify that you run these commands from the `cli` folder (if run from the parent folder then it needs to be `npx link cli`).

docs: update CLI dev env setup instructions

---

cli/src/cli.spec.ts

In `cli.spec.ts`, it was doing an `npm link` even though in the docs is says not to do that. This means the tests were failing if you weren't running as an account that could modify the global `node_modules`. I've changed this to use `npx link` instead.

tests: fix problem with running tests when not root

---

.flox/env/manifest.lock
.flox/env/manifest.toml
cli/DEVELOPER_GUIDE.md

Node v21 is also compatible with `canvas`, so bumping the recommended version and updating the Flox environment to match.

maint: bump recommended Node version to 21 and auto-install Java dependencies

---

.flox/env/manifest.lock
.flox/env/manifest.toml
cli/DEVELOPER_GUIDE.md

Following merging of https://github.com/finos/architecture-as-code/pull/700 node 22 is now supported by canvas.
```shell
flox [calm] ~/architecture-as-code % flox list
gum: gum (0.14.5)
jdk21: jdk21 (zulu-ca-jdk-21.0.4)
maven3: maven3 (maven-3.9.9)
nodejs_22: nodejs_22 (nodejs-22.11.0)
flox [calm] ~/architecture-as-code % npx calm --version
0.3.0
```

Upgrade node too v22 now canvas has been upgraded to v3

---

calm-hub/deploy/docker-compose.yml

As per comment https://github.com/finos/architecture-as-code/pull/799#discussion_r1923571270, reverting back change to docify-compose file to allow people to run calm-hub without build.

Revert back docify-compose.yml change so that calm-hub can run without build

---

calm-visualizer/src/components/cytoscape-renderer/CytoscapeRenderer.tsx
calm-visualizer/src/components/cytoscape-renderer/cytoscape.css

I noticed that the small nodes, which are white in colour, don't get highlighted when you click on them, while the edges do. It would be nice to see which node corresponds to the sidebar which opens, hence I made this PR where the selected white nodes are highlighted.
The reason highlighting was not happening earlier was because these nodes were all being given a static html template for a label. I tweaked this a little to give a new node label template if the node has the `:selected` class. The result looks like this:
Note that:
- If we close the sidebar, the node on the graph does not get deselected.
- If we deselect on the graph (by clicking outside it), the sidebar does not get closed
This behaviour is easy enough to change, but I thought I'd keep things simple in this PR e.g. do …

Highlight the small nodes on selection

---

calm-visualizer/package.json
cli/src/index.ts
package.json
shared/src/commands/generate/generate.e2e.spec.ts
shared/src/commands/validate/validate.spec.ts
shared/src/commands/validate/validate.ts
shared/src/index.ts
shared/src/schema-directory.spec.ts
shared/test_fixtures/api-gateway-implementation.json

Addresses #831 
- validate command now defers to SchemaDirectory for all spec loading
- validate command no longer calls process.exit() - that is deffered to the calling module (there is a helper method validateAndExitConditionally)
- big improvements to the validate command tests
- add a cli test script that always builds first to eliminate strange link issues

Rework validate command to use SchemaDirectory, and clean up process.exit() use

---

.github/workflows/build-cli.yml
.github/workflows/build-shared.yml
.gitignore
cli/jest.config.js
shared/jest.config.js

This PR introduces basic coverage generation for the project. The build will now **fail** if the coverage thresholds are not met, providing an early indication of insufficient test coverage. This is a foundational change to ensure we have consistent coverage metrics going forward.
- **Basic Coverage Generation**: 
- Jest is configured to collect and report test coverage.
- A summary of coverage statistics will be generated after each test run.
- **Coverage Failure Thresholds**:
- The current coverage thresholds are set to pass the build, but these are placeholders for future configuration.
- The limits are currently configured in a way that will not break the build but will ensure that coverage is collected and monitored.
- The coverage thresholds are temporarily set to pass the build. …

Add code coverage and break build

---

calm/draft/2025-01/meta/core.json
calm/draft/2025-01/meta/flow.json
shared/src/model/control-requirement.spec.ts
shared/src/model/control-requirement.ts
shared/src/model/control.spec.ts
shared/src/model/control.ts
shared/src/model/core.spec.ts
shared/src/model/core.ts
shared/src/model/flow.spec.ts
shared/src/model/flow.ts
shared/src/model/interface.spec.ts
shared/src/model/interface.ts
shared/src/model/metadata.spec.ts
shared/src/model/metadata.ts
shared/src/model/node.spec.ts
shared/src/model/node.ts
shared/src/model/relationship.spec.ts
shared/src/model/relationship.ts
shared/src/parser/parser.e2e.spec.ts
shared/src/parser/parser.ts
shared/src/types.ts
shared/src/types/control-requirement-types.ts
shared/src/types/control-types.ts
shared/src/types/core-types.ts
shared/src/types/flow-types.ts
shared/src/types/interface-types.ts
shared/src/types/metadata-types.ts
shared/src/types/units-types.ts

This PR introduces a centralized and structured data model for CALM. Per discussion on https://github.com/finos/architecture-as-code/issues/899, The new model provides well-defined TypeScript classes and enums for core CALM components, ensuring seamless integration and validation for cli and visualizer componenets. 
- Added types that match the current schema files.
- Introduced `CalmCore` as the centralized entry point for nodes, relationships, metadata, controls, and flows.  
- Standardized structure for `CalmNode`, `CalmRelationship`, `CalmFlow`, `CalmControl`, and `CalmMetadata`.  
- Each model includes a `fromJson()` factory method to enable seamless conversion from JSON.  
- Ensures consistent handling of nested objects, such as relationships and interfaces.  
- Added unit tests for …

New centralised model for CALM (#790)

---

docs/DEVELOPER_GUIDE.md

Developer guide didn't actually contain any instructions on how to build or locally test the docs.  It does now.

docs: update developer guide for docs

---

cli/jest.config.js
cli/src/cli.e2e.spec.ts
cli/src/cli.spec.ts
cli/src/index.ts
cli/src/validate/validate.spec.ts
cli/src/validate/validate.ts
cli/test_fixtures/template/model/document-system.json
cli/test_fixtures/template/template-bundles/doc-system/basic-transformer.js
cli/test_fixtures/template/template-bundles/doc-system/index.json
cli/test_fixtures/template/template-bundles/doc-system/main.hbs

This PR enhances the test coverage for the CLI. Coverage was not being puc
✅ **Renamed `cli.spec.ts` → `cli.e2e.spec.ts`** since it was acting as an integration test rather than a unit test.  
✅ **Added a new e2e test (`cli.e2e.spec.ts`)** to properly test the `calm template` command by executing it as a subprocess. 
✅ **Created new CLI unit tests (`cli.spec.ts`)** to properly mock CLI behavior without spawning subprocesses.  
✅ **Refactored CLI validation logic** by extracting it from `index.ts` into a separate module, improving testability and separation of concerns.  
- **🔍 Improves Test Coverage**: The CLI subprocess was not being counted in coverage, leading to misleading results i.e. coverage report wasn't covering index.ts
- **📂 Better Test Structure**: Separates **unit tests** …

Refactor CLI to add more test coverage and add e2e test in cli for calm template endpoint (#890)

---

calm/draft/2025-03/meta/units.json
calm/draft/2025-03/prototype/throughput-control-prototype.json

This PR enhances the **units.json** schema within **CALM** to support rate-based values, such as "30 per second." 
- Introduces a **`rate-unit`** definition to represent rate-based values.
- Added example in prototype folder.

Create new rate type in units.json (#1038)

---

cli/README.md
cli/src/index.ts

This PR enhances the CLI documentation by adding details for two newly introduced commands:  
`calm template` ([Issue #890](https://github.com/finos/architecture-as-code/issues/890))  
`calm docify` ([Issue #478](https://github.com/finos/architecture-as-code/issues/478))  
These additions improve the discoverability and usability of these features for developers working with CALM models.

Add cli documentation for calm template and calm docify endpoints (#890)(#478)

---

cli/package.json
cli/src/cli.e2e.spec.ts
package-lock.json
shared/package.json

The following issue fixes issue1 with tsnode and json-ref-parser libraries not being installed as part of the calm cli (a pre-requisite for the `calm template` endpoint
The cli.e2e.spec.ts now leverages npm pack to simulate the actual package that npm publishes and simulates a consumer installing calm from npm in an isolated node environment. Going forward this test now gives full confidence on cli endpoints.

Fix global install issues with cli (#1043)

---

calm/pattern/api-gateway.json
cli/package.json

In order to use `calm generate` without specifying a schema directory, we need to copy over latest version

Ensure SchemaDirectory works with latest CALM draft

---

shared/src/template/template-bundle-file-loader.ts
shared/src/template/template-default-transfomer.spec.ts
shared/src/template/template-default-transformer.ts
shared/src/template/template-processor.e2e.spec.ts
shared/src/template/template-processor.spec.ts
shared/src/template/template-processor.ts
shared/src/template/types.ts
shared/test_fixtures/template/bundles/default-transformer/index.json
shared/test_fixtures/template/bundles/default-transformer/main.hbs
shared/test_fixtures/template/data/controls/architect.configuration.json
shared/test_fixtures/template/data/controls/business-owner.configuration.json
shared/test_fixtures/template/data/controls/owner-responsibility.requirement.json
shared/test_fixtures/template/data/controls/system-owner.configuration.json
shared/test_fixtures/template/data/document-system-with-controls.json
shared/test_fixtures/template/expected-output/doc-system-one-pager.md

This PR introduces a fallback mechanism to use a Detault Transfomer when a template bundle does not explicitly define a transformer in its `index.json`.
Closes #1106 
This change streamlines template development by removing boilerplate requirement to write a transformer for simple use cases and improves out-of-the-box usability of the `calm template` endpoint.

CALM Template to support DefaultTransformer (#1106)

---

calm-hub/src/main/resources/application-secure.properties
calm-hub/src/main/resources/application.properties

- Set `quarkus.oidc.enabled` build-time configuration to `false` 
TODO: As this is OIDC, enablement is a build-time configuration; either we have to build a dedicated Docker image for the secure profile, or I'll find a way to set enable as a runtime configuration.

finos#1081 set quarkus.oidc.enabled build-time configuration to false

---

calm-hub-ui/src/visualizer/Visualizer.tsx
cli/package.json

In reference to issue #1113, the bug has been fixed, and architectures can now be rendered from Calm Hub or by manual upload.
@oliviajanejohns @DorothyEwuah @aidanm3341 @aamanrebello

#1113  fixed cyctoscape render bug on upload

---

calm-hub-ui/src/visualizer/components/cytoscape-renderer/CytoscapeRenderer.tsx
calm-hub-ui/src/visualizer/components/cytoscape-renderer/cytoscape.css
calm-hub-ui/src/visualizer/components/drawer/Drawer.tsx

Refer to conversation for latest updates.
UI at present:
How it looks on api-gateway
How it looks on traderX

Expand nodes to fit description labels

---

cli/test_fixtures/generate_output.json
package-lock.json
shared/src/commands/generate/components/instantiate.spec.ts
shared/src/commands/generate/components/instantiate.ts
shared/test_fixtures/command/generate/expected-output/conference-secure-signup.arch.json
shared/test_fixtures/command/generate/expected-output/conference-signup.arch.json
shared/test_fixtures/template/data/conference-secure-signup.amended.arch.json

Addresses #1201
Since the refactor `calm generate` selects the `$schema` property of the pattern when generating. It should be `$id` instead.

Output correct $schema when generating (#1201)

---

cli/package.json
shared/src/spectral/functions/pattern/interface-id-exists-on-node.ts

The existing spectral rule was crashing when it failed to find a node, e.g. if it was inside a oneOf or anyOf block

(fixes #1210) fixed validate crash

---

calm-hub/pom.xml
calm-hub/src/main/java/org/finos/calm/resources/CoreSchemaResource.java

Standardized library used to sanitize. Core Schema is inserted by the mongo init script so cannot enforce pattern format.
Follow up change will add patterns to other controllers to avoid need to directly sanitize.
fixes #961

(fixes #961) sanitize error responses from CoreSchemaResource controller

---

calm-hub-ui/package.json
package-lock.json
shared/src/docify/template-bundles/docusaurus/docusaurus-transformer.ts
shared/src/template/template-processor.ts
shared/tsup.config.ts

Puts in an additional fix for https://github.com/finos/architecture-as-code/pull/1263 so that vite can be upgraded.

 update dependency vite to v6.3.4 [security] + associated test fix

---

calm/release/1.0-rc1/meta/flow.json
shared/src/model/control.spec.ts
shared/src/model/control.ts
shared/src/model/core.spec.ts
shared/src/model/core.ts
shared/src/model/interface.spec.ts
shared/src/model/interface.ts
shared/src/model/relationship.spec.ts
shared/src/model/relationship.ts
shared/src/types/control-types.ts
shared/src/types/core-types.ts
shared/src/types/interface-types.ts
shared/test_fixtures/template/bundles/default-transformer/main.hbs
shared/test_fixtures/template/data/document-system-with-controls.json
shared/test_fixtures/template/expected-output/doc-system-one-pager.md

This PR contains a start of changes in the cli to support the new release candidate.  The PR focuses mainly on type changes. 
- Removed `metadata` definition from `flow.json` (was previously a duplicate).
- Updated the `$ref` to metadata to point to `core.json#/defs/metadata` for consistency.
Option/Decision Schema Support - https://github.com/finos/architecture-as-code/pull/931
ADRs on core.json - https://github.com/finos/architecture-as-code/pull/1268
Support for custom interfaces - https://github.com/finos/architecture-as-code/issues/1083
Support for inline controls - https://github.com/finos/architecture-as-code/issues/1233
Updated one test to show how inline controls can work within the template. 
Docify templates update to happen on subsequent PR

Fix cli types based on 1.0-rc CALM spec (#1284)

---

calm-hub-ui/src/visualizer/components/menu/Menu.test.tsx
calm-hub-ui/src/visualizer/components/menu/Menu.tsx

In relation to https://github.com/finos/architecture-as-code/issues/1190
Before: After uploading file, user has to click outside to close the dropdown. It also interfered with the node/edge details section on the right.
Above change avoids that since we only have one option and hence uses a button directly.

Issue 1190: Update upload button to avoid expand/collapse issue

---

calm/pattern/api-gateway.json
calm/release/1.0-rc1/meta/core.json
calm/release/1.0-rc1/meta/interface.json
calm/release/1.0-rc1/prototype/anyof/both-options.architecture.json
calm/release/1.0-rc1/prototype/anyof/neither-option.architecture.json
calm/release/1.0-rc1/prototype/anyof/options-prototype.pattern.json
calm/release/1.0-rc1/prototype/multiple-choices/architecture.json
calm/release/1.0-rc1/prototype/multiple-choices/options-prototype.pattern.json
calm/release/1.0-rc1/prototype/oneof/application-a.architecture.json
calm/release/1.0-rc1/prototype/oneof/application-b.architecture.json
calm/release/1.0-rc1/prototype/oneof/options-prototype.pattern.json
calm/release/1.0-rc1/prototype/throughput-control-prototype.json
calm/workshop/architecture/conference-secure-signup-amended.arch.json
calm/workshop/conference-secure-signup.pattern.json
calm/workshop/conference-signup.pattern.json
calm/workshop/controls/micro-segmentation.requirement.json
calm/workshop/controls/permitted-connection.requirement.json
calm/workshop/directory.json
cli/README.md
cli/package.json
cli/src/cli.e2e.spec.ts
cli/src/server/routes/validation-route.spec.ts
shared/src/commands/generate/components/options.spec.ts
shared/src/commands/generate/generate.e2e.spec.ts
shared/src/consts.ts
shared/src/template/template-processor.e2e.spec.ts
shared/test_fixtures/template/data/controls/owner-responsibility.requirement.json

Update all test files to work with new `rc1` candidate of the CALM schema.  This update ensures compatibility across the test suite and confirms that the `rc1` schema is included in the distributed package.
- Development of code to make it less dependent on specific calm versions by hydrating schema registry with different schema versions.  See [architecture-as-code#836 (comment)](https://github.com/finos/architecture-as-code/issues/836#issuecomment-2884423305)
---

Update endpoints and test files related to validate/generate endpoints inline with RC-1 (finos#1284)

---

calm-hub-ui/src/visualizer/components/cytoscape-renderer/CytoscapeRenderer.test.tsx
calm-hub-ui/src/visualizer/components/cytoscape-renderer/CytoscapeRenderer.tsx

- Added the ability for the pan and zoom to be maintained between rerenders (i.e. when you clicked on a node, or when you used the toggles in the tool bar etc.)
- Fixed the bug where the container-like relationships were being incorrectly rerendered on every rerender
- Added some basic unit tests for the CytoscopeRenderer component

#1234 added persisting of pan and zoom between renders and fixed repositioning bug on rerender

---

calm/release/1.0-rc2/RELEASE_NOTES.md
calm/release/1.0-rc2/meta/core.json
calm/release/1.0-rc2/prototype/meta-example.json

This PR adds support for having `metadata` be either a single object **or** an array of objects, and updates the v1.0‑rc2 **README.md** release‑notes with:
- A new **“Metadata Flexibility”** section under **Major Changes**
- Migration guidance for the new metadata format
- Adjusted section numbering to accommodate the new content
No other schema breaking changes are introduced.
---
1. **Schema Definition**  
- Updated `defs.metadata` in `core.json` to:
```json
"metadata": {
"oneOf": [
{ "type": "array", "items": { "type": "object" } },
{ "type": "object", "additionalProperties": true }
]
}
```
2. **README.md**  
- Added **“5. Metadata Flexibility”** under **Major Changes**  
- Added **“6. Metadata Format Flexibility”** under the **Migration Guide**  
- Renumbered existing items to keep …

Add Metadata Flexibility & Update v1.0-rc2 Release Notes

---

conferences/osff-ln-2025/workshop/architecture/conference-secure-signup-amended.arch.json
conferences/osff-ln-2025/workshop/conference-secure-signup.pattern.json
conferences/osff-ln-2025/workshop/directory.json
conferences/osff-ln-2025/workshop/flows/conference-signup.flow.json
shared/src/commands/generate/components/instantiate.spec.ts
shared/src/commands/generate/components/instantiate.ts
shared/src/docify/docifier.e2e.spec.ts
shared/test_fixtures/command/generate/expected-output/conference-secure-signup-amended.arch.json
shared/test_fixtures/command/generate/expected-output/conference-secure-signup.arch.json
shared/test_fixtures/docify/workshop/expected-output/secure/docs/flows/flow-conference-signup.md
shared/test_fixtures/docify/workshop/expected-output/secure/docs/index.md
shared/test_fixtures/docify/workshop/expected-output/secure/sidebars.js
shared/test_fixtures/template/data/conference-secure-signup.amended.arch.json

The `instantiateFromProperties` function in the `instantiate.ts` file has been modified with three key changes:
This allows support in the pattern like this
```json
"flows": {
"type": "array",
"minItems": 1,
"maxItems": 1,
"prefixItems": [
{
"const": "https://calm.finos.org/workshop/flows/conference-signup.flow.json"
}
]
}
```

Add support for flows inside pattern using const to a url reference + confirm generated arch document renders flow in docify

---

cli/test_fixtures/template/expected-output/widget-tests/json-viewer-test.md
cli/test_fixtures/template/widget-tests/flow-sequence-test.hbs
cli/test_fixtures/template/widget-tests/json-viewer-test.hbs
package-lock.json
shared/package.json
shared/src/template/template-preprocessor.spec.ts
shared/src/template/template-preprocessor.ts

Fixes pre-parsing of DotNotation in certain situations as mentioned and concluded on https://github.com/finos/architecture-as-code/issues/1556#issuecomment-3243213264 
```hbs
{{json-viewer nodes['load-balancer'] }}
```
The logic has been altered to be less aggressive in passing paths to the convertToDotNotation helper function. In addition adds diagnostics to the pre-parsing and defaults this context if not specified
```hbs
{{flow-sequence flow-id="test"}}
```

feat(calm-widgets): imply context if not specified and fix dot notation bugs

---

calm-plugins/vscode/package.json

Change the VScode publisher to FINOS to allow publishing to market place

fix(calm-plugins): change publisher to FINOS

---

calm-plugins/vscode/README.md
calm-plugins/vscode/package.json

On the latest published version https://marketplace.visualstudio.com/items?itemName=FINOS.calm-vscode-plugin, images are not rendering.  Upon re-reading https://code.visualstudio.com/api/working-with-extensions/publishing-extension#marketplace-presentation-tips, one needs to refer to https urls.
Fix images on marketplace entry

docs(calm_plugins): Fixing images as vscode marketplace requires https urls
